swiftmailer:
    url: '%env(MAILER_URL)%'
    transport: smtp
    host: smtp.sendgrid.net
    port: 587
    encryption: tls
    auth_mode: login
    username: '%env(SENDGRID_USERNAME)%'
    password: '%env(SENDGRID_PASSWORD)%'